export const CartTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREMENT_QUATITY: 'INCREMENT_QUATITY',
    DECREMENT_QUATITY: 'DECREMENT_QUATITY'
}
